<?php
return [
    'missing_params' => '缺少必要参数',
    'invalid_credentials' => '用户名或密码错误',
    'invalid_refresh_token' => '无效的刷新令牌',
    'user_not_found' => '用户不存在',
    'request_id_duplicate' => '请求ID重复',
    'invalid_phone' => '无效的手机号',
    'phone_exists' => '手机号已存在',
    'no_update' => '没有需要更新的数据',
    'file_not_uploaded' => '未上传文件',
    'db_insert_failed' => '数据库插入失败',
    'exam_disabled' => '考试未启用',
    'already_submitted' => '已提交考试',
    'no_answers' => '没有提交的答案',
    'exam_not_found' => '考试不存在',
    'exam_not_started' => '考试尚未开始',
    'missing_token' => '缺少认证令牌',
    'invalid_token' => '无效的认证令牌',
    'unauthorized' => '无权限访问',
    'question_not_found' => '题目不存在',
    'question_content_too_long' => '题目内容过长',
    'invalid_type' => '无效的题目类型',
    'invalid_params' => '无效的参数',
    'options_exceed' => '选项数量超出限制',
    'invalid_answer_format' => '答案格式无效',
    'insufficient_questions' => '题目数量不足',
    'request_not_found' => '请求不存在'
];